name: Vercel Auto-Deployment on Main Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERCEL_ORG_ID: team_XzZzyCkJG7q9PWarWt7O158U
  VERCEL_PROJECT_ID: prj_a1tblY4sfY3atG22ZLHsEC6vU4ge

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Vercel Production
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
